baseURL = "https://www.afs.enea.it/puccini/"
languageCode = "en-us"
title = "marcopuccini@enea"
theme = "researcher"
enableEmoji = true


[params]
  [params.profile]
    author = "Marco Puccini"
    description = "A simple w."
    favicon = "/puccini/favicon.ico"  # path to a .ico to use as favicon
    enable = true
    avatar = "/puccini/imgs/avatar.jpg"
    name = "Marco Puccini"
    # #    bio = "XXX"  # support markdown syntax
    #     twitter = "XXX"  # https://twitter.com/XXX
    github = "https://github.com/mpuccini"  # https://github.com/XXX
    # #    docker = "XXX"  # https://hub.docker.com/u/XXX
    email = "marco.puccini@enea.it"  # mailto:XXX@mail.com
  [params.footer]
    text = "Built with Hugo theme Researcher"
    url = "https://themes.gohugo.io/hugo-researcher/"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "950px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [params.math]
    enable = true  # true means globally, or on a per page set "math = true"
    use = "katex"  # "mathjax" or "katex"
  [params.syntax]
    use = "hljs"  # builtin: "prismjs", "hljs". "none" means Chroma
    theme = "dracula"
    darkTheme = "xcode-dark"  # apply this theme in dark mode

[permalinks]
  "/" = "/:filename"
  "/imgs" = "/imgs/:filename"

[menu]
  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "projects"
    url = "/projects"
    weight = 2
  [[menu.main]]
    name = "publications"
    url = "/publications"
    weight = 3
  [[menu.main]]
    name = "contacts"
    url = "/contacts"
    weight = 4
  [[menu.main]]
    name = "resume"
    url = "/docs/puccini_eurocv.pdf"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[taxonomies]
  tag = "tags"
